### PR TITLE
Handle Missing Data

### PR DESCRIPTION
**Pull request by convoliution**
## Changes
Processors now simply return unchanged `state` when:
- the key is missing
- the value is `None`

## Notes
An `IndexError` would still be raised, because it suggests a malformed input. A proper list with missing data should be the correct length, but with `None`s for missing values!

### CODE REVIEW

File: verta/verta/monitoring.py [hunk 1]
```diff
@@ -204,20 +207,19 @@ def _reduce_data(self, state, data):
         # get feature value
         feature_name = self.config['feature_name']
         try:
-            feature_val = data[feature_name]
-        except KeyError:
-            six.raise_from(KeyError("key '{}' not found in data".format(feature_name)), None)
+            feature_val = data.get(feature_name, None)
         except TypeError:  # data is list instead of dict
```
Comment (conradoverta) [inline verta/verta/monitoring.py]: Should this be AttributeError?
```
>>> a=[1]
>>> a.get('foo')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'list' object has no attribute 'get'
```

I'd highly recommend checking the type and making a decision instead of blindly trying things and catching exceptions. This is bad practice.

Comment (convoliution) [reply verta/verta/monitoring.py]: 😱
